Update EarthGlove.java
Could not pass event PlayerInteractEvent to Hyperion v1.7.0
java.lang.NullPointerException: Cannot invoke "me.moros.hyperion.abilities.earthbending.EarthGlove$Side.ordinal()" because "s" is null
    at Hyperion-1.7.0.jar//me.moros.hyperion.abilities.earthbending.EarthGlove.getCooldownForSide(EarthGlove.java:314)